import React from 'react';
import { Brain, Info, ShieldAlert } from 'lucide-react';

interface ExplainableAIPanelProps {
  rationale: string[];
  confidence: number;
}

const ExplainableAIPanel: React.FC<ExplainableAIPanelProps> = ({ rationale, confidence }) => {
  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2 text-sm font-medium text-ps-text-muted">
          <Brain size={16} className="text-ps-primary" />
          AI Rationale
        </div>
        <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-ps-primary/10 text-ps-primary text-xs font-semibold">
          {Math.round(confidence * 100)}% Confidence
        </div>
      </div>

      <div className="space-y-3 flex-1 overflow-y-auto">
        {rationale.map((point, idx) => (
          <div key={idx} className="flex gap-3 p-3 rounded-lg bg-ps-bg/50 border border-ps-border">
            <div className="mt-1">
              <Info size={14} className="text-ps-text-muted" />
            </div>
            <p className="text-sm text-ps-text leading-relaxed">
              {point}
            </p>
          </div>
        ))}
      </div>

      <div className="mt-4 pt-4 border-t border-ps-border">
        <div className="flex items-center gap-2 text-xs text-ps-text-muted">
          <ShieldAlert size={14} className="text-amber-500" />
          These insights are generated by Gemini 2.0 Flash based on current diff patterns.
        </div>
      </div>
    </div>
  );
};

export default ExplainableAIPanel;
